name: matches
description: Utility classes that are useful already, but will become even more useful when Dart 3 arrives
version: 1.0.0
repository: https://github.com/lesnitsky/matches

environment:
  sdk: ">=3.0.0-233.0.dev <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
